[package]
name = "metamusic"
version = "0.1.0"
edition = "2024"
description = "TUI mp3 tags editor"
license-file = "LICENSE"

[dependencies]
crossterm = "0.29.0"
id3 = "1.16.3"
image = "0.25.9"
inquire = "0.9.1"
ratatui = "0.29.0"
ratatui-image = "8.0.2"
